FROM node:22-alpine3.22

# Set the working directory inside the container
WORKDIR /app
 
# Copy package.json and package-lock.json
COPY package*.json ./
 
# Install dependencies
RUN npm config set strict-ssl false
RUN npm install
 
# Copy the rest of your application files
COPY . .
 
# Expose the port your app runs on
ENV PORT=5173
EXPOSE 5173
 
# Define the command to run your app
CMD ["npm", "run", "dev", "--", "--host"]
