services:
  # Backend Application Service
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: myproject-backend:latest
    container_name: backend
    restart: unless-stopped
    env_file :
      - backend/.env
    ports:
      - "8000:8000"
    networks:
      - di-network
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: myproject-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - di-network
    depends_on:
      - backend

networks:
  di-network:
    driver: bridge